name: mood_to_matcha
description: "A Flutter project for Mood To Matcha app."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  cached_network_image: ^3.3.1
  table_calendar: ^3.0.9
  http: ^1.2.0
  intl: ^0.19.0
  url_launcher: ^6.3.0
  geolocator: ^12.0.0
  geocoding: ^3.0.0
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  permission_handler: ^11.0.0
  path: ^1.9.0
  sqflite: ^2.4.0
  path_provider: ^2.1.3
  flutter_local_notifications: ^18.0.1
  timezone: ^0.9.2
  get_storage: ^2.1.1
  crypto: ^3.0.3
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/nelaprofile.png
